language: objective-c
osx_image: xcode7.2
xcode_project: SKUtils.xcodeproj
xcode_scheme: SKUtils
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew install carthage
  - carthage update --platform iOS
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --platform iOS
before_deploy:
  - carthage build --no-skip-current --platform iOS
  - carthage archive SKUtils

deploy:
  provider: releases
  api_key:
    secure: kB27dXDvTOCk6OZAStzIdvVL6OH2KoDgqPWYcvJr8bx3amXzOYmmL/rEHqoldMwkXnQnI2vgNTONYSYitppw87TORmTFFby3fsDUDeZc6SIzv9KvL3d7Yd1GFHI4hzylB9We94qFIP4jKkLw7vABhISK5fUOMSg4O17l/+uAAQQ5IOwsRKbA3Co/vjEtw3EeH8V2xECBJuIICdoRPfcEHJm8g0OoTh7QhpZs2Olate+sXx7RgbibPFVZWDxgdJ0NVMhfOxsjLmwvcJ92xkbinkpzvmX/cN+5NZQSBHimz/wOuWkjA2D72TUpR+E+YpWlljpLoE+GOz9YAUl/UXcc4sdJ8xfcObJb4DpNYljv65QqP6+G4PT7TtvB58qQSEH+reHxiapkwa3NvYyQmgcUbng0ld2glJLWAyjoO9bs2MGhP/il9dbp9Vo9shkIl4wVSG3ZOlSSL7k3wP1B3VowSWEqNDH6AX/pKtzPU59PJsP1jDc1ioxCU667xVC45dnL3lDdCvIANSPb4W1H+9P7QUWNwjz7qzHAijLJa7SI6feIZ3ED22icBZHfN5E1jTx4gIvmBhzSFSrIUK7T4at1bTGxsN2nGVpSxCDd29wiPCZupm4SwOxD8itp9iFEGVTEW5dKQqpP31okrIgUSgfSRoLsosOKcTf/6rg9zYT/f28=
  file: SixUtils.framework.zip
  skip_cleanup: true
  on:
    tags: true
