language: objective-c
osx_image: xcode7.2
xcode_project: SKUtils.xcodeproj
xcode_scheme: SKUtils
xcode_sdk: iphonesimulator
before_install: 
  - brew update
  - brew upgrade xctool
  - brew install carthage
  - carthage update --platform iOS
