language: objective-c
osx_image: xcode7.2
xcode_project: SKUtils.xcodeproj
xcode_scheme: SKUtils
xcode_sdk: iphonesimulator
before_install:
before_script:
- carthage bootstrap --platform iOS
before_deploy:
- carthage build --no-skip-current --platform iOS
- carthage archive SKUtils
deploy:
  provider: releases
  api_key:
    secure: pUkB5IecV7Qb/bSDor4TE+HuZ5p8FPnP8ciL2M2SxKwAG8shIc6MgeQYU3ZbdaO3fETpUHpoD/9y3Xkx8gmkLYGU1vb+DuQsyZ21hWfA1khcDrEqDxv4c8mmEmHIFidcgwuvtzGyzEf5xO3mnROktbYp01ux6EGlncHmD2oUnirr96XarxkAJ7/1QPIJ34XrmswgdD+vDJvhwmotbwHa4Y1WfGs6Vufe8nAjk2/sbQ1FglRXQCEghbjdW5BJOP4DTgZRu4XpFo1YWM+QvsocDiDyqFPFbqz1FwdDdMHvF2M0QRoJhVeEykZaoqYR5yi5eAhZQ6+DykP0ebmyu2frCWBAG2VN0VmEctMb1iQTSOamkjZKjhCFmn4wGj1aMhUObYBLZshUughoV13dhZuCdaUzE/FmhwQ6wnp4MnbuRByrO1zD3G+A+WDHIQrkL69rmmdSAIxEdrTP5r0E5zRbPhQh706ESnwXV84l7kopbtaGJ1s0uols/7DH3qBrS03z7rYJeJCHvvxPYoWzh7b1ma5aVZ8eIy4YSLAn8bbZHt/pnPjFma83iNf2XlBuO81BF+VxTGLuF6puX3l4/PhoEzebzN0EkP2UYtaYxNObi7EoDCk02M1yyTFqPifpJjP0ijF57PBLIZmAVsFMvX2G3CPTj3ZHsLV/YS3DdSv97Hk=
  file: SKUtils.framework.zip
  skip_cleanup: true
  on:
    repo: skchen/SKUtils
    tags: true
